default_platform(:ios)
skip_docs

platform :ios do
    lane :test do |options|
        ci = ENV['CI']
        puts 'Running on CI.' if ci

        version = options[:version].to_i || 16

        if version == 13
            # we only build, not test, on iOS 13
            gym(
                skip_archive: true,
                workspace: "Introspect.xcworkspace",
                scheme: "Introspect",
                sdk: "iphoneos13.7",
            )
            # we only build, not test, on tvOS 13
            # gym(
            #     skip_archive: true,
            #     workspace: "Introspect.xcworkspace",
            #     scheme: "Introspect",
            #     sdk: "appletvos13.4",
            # )
            next
        end

        devices = case version
        when 14
            [
                "iPhone 11 Pro (14.5)",
                "iPad Pro (11-inch) (3rd generation) (14.5)",
                # "Apple TV (tvOS 14.5)",
            ]
        when 15
            [
                "iPhone 11 Pro (15.5)",
                "iPad Pro (11-inch) (3rd generation) (15.5)",
                # "Apple TV (tvOS 15.4)",
            ]
        when 16
            [
                "iPhone 14 Pro (16.2)",
                "iPad Pro (11-inch) (4th generation) (16.2)",
                # "Apple TV (tvOS 16.1)",
            ]
        else
            raise "Unsupported iOS version: #{version}"
        end

        run_tests(
            scheme: "Introspect",
            devices: devices,
            ensure_devices_found: true,
        )
    end
end

platform :mac do
    lane :test do |options|
        puts 'Running on GitHub CI.' if options[:ci] == 'github'
        scan(
            scheme: "Introspect macOS",
            skip_build: options[:ci] == 'github'
        )
    end
end
